<table width="100%" height="100%"  border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td align="left" valign="top">~</td>
    <td width="220" rowspan="2" align="center" valign="top" background="/jjj/layout/s1.jpg" bgcolor="#6072A0" style="border-left: 1px solid black; background-repeat: no-repeat;">~<table width="200" height="370" border="0" cellpadding="0" cellspacing="0">
      <tr>
        <td width="35" rowspan="4"><img src="/jjj/layout/n1.gif" width="35" height="370" border="0"></td>
        <td align="left" valign="top"><img src="/jjj/layout/n2.gif" width="130" height="77" border="0"></td>
        <td width="35" rowspan="4"><img src="/jjj/layout/n3.gif" width="35" height="370" border="0"></td>
      </tr>
      <tr>
        <td width="130" height="91" align="center" valign="top" background="/jjj/layout/n4.gif">Not Available </td>
      </tr>
      <tr>
        <td align="left" valign="top"><img src="/jjj/layout/n5.gif" width="130" height="73" border="0"></td>
      </tr>
      <tr>
        <td width="130" height="129" align="center" valign="top" background="/jjj/layout/n6.gif">Not Available</td>
      </tr>
    </table>~
      <table width="200" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td height="31"><img src="/jjj/layout/ad1.gif" width="200" height="31"></td>
        </tr>
        <tr>
          <td height="100" align="center" valign="top" background="/jjj/layout/ad3.gif"><ad:skyscraper></td>
        </tr>
        <tr>
          <td height="11"><img src="/jjj/layout/ad4.gif" width="200" height="11"></td>
        </tr>
      </table></td>
  </tr>
  <tr>
    <td align="left" valign="bottom" style="padding: 0px 0px 10px 10px;"><ad:banner></td>
  </tr>
</table>